version: '3'

services:

  #nginx:
  #  image: nginx:alpine
  #  restart: always
  #  ports:
  #    - "8080:80"
  #  volumes:
  #    - ./nginx/sites/nginx.conf:/etc/nginx/nginx.conf:ro
  #    #- ./nginx/conf.d/default.conf:/etc/nginx/default.conf:ro
  #    #- ./nginx/modsecurity.conf:/etc/nginx/modsecurity.conf:ro
  #    - ./myfrontend/build:/usr/share/nginx/html:ro

  frontend:
    build:
      context: ./myfrontend
    command: npm run start  # Use this for React development mode
    volumes:
      - ./myfrontend:/app
      - ./build:/app/build
    ports:
      - "3000:3000"  # Expose the frontend on port 3000
    environment:
      - NODE_ENV=development
    restart: unless-stopped 

    stdin_open: true
    tty: true

